### ISSUE TITLE
Torque slows down requests

### ISSUE THREAD

**Issue by smarquez1** [crashtech/torque-postgresql#42]
Hi, I just installed `torque-posgresql` and while it works very well it really slows down my application.
I created a dummy Rails app with a seed file to test this, and just by including the gem my requests are being slowing down:

```
time curl localhost:3000/projects.

# Adding torque-postgresql 1.1.1 to Gemfile
1st request 9.44s
2nd request 7.6s

# Commenting out torque-postgresql from Gemfile
1st request 1.11s
2nd request 599ms
```

Tested in development using:
Rails 5.2.4
Ruby 2.5.5p157
Postgresql 12.1

Dummy Rails App: https://github.com/smarquez1/torque_test

**Comment by smarquez1** [comment]
After some debugging, I found out that this method is the reason of what's slowing down the requests. Looks like need a faster way of checking if the models table depends on any inheritance

**Comment by crashtech** [comment]
Sounds very reasonable! But just checking `@inheritance_dependencies.nil?` won't work, maybe `return unless @inheritance_dependencies.nil?`, because it needs to be able to load once at least, even if that means returning an empty Hash.

I could also early return when having no dependency at all.

Another cool thing about your observation is that we could use `flamegraph` and `rack-mini-profiler` gems to dive a little deeper and check if what's holding the request is a query, a process, or multiple unnecessary calls.

Let me know what you think @smarquez1. Since the fix seems pretty simple, I might even do it in the next few days.

**Comment by smarquez1** [comment]
Thanks for the fix @crashtech, that was fast! After the holidays I'll look into applying those gems to the project, It'd be very interesting to learn them.

Happy holidays!
